### ISSUE TITLE
App icon following GNOME's guidelines

### ISSUE THREAD

**Issue by bragefuglseth** [zhrexl/ThisWeekInMyLife#3]
This Week In My Life utilizes GNOME's platform libraries, but the current app icon looks out of place among other GNOME apps. I think the app would benefit from having an icon with [GNOME's distinct visual style](https://developer.gnome.org/hig/guidelines/app-icons.html).

I can design one if you want me to. I'll start brainstorming, but feel free to stop me if you don't consider it to be necessary :smile: 

As a sidenote, the app name seems a little long. Wouldn't something a little shorter, like "Schedule", be more convenient to spell / type out?

**Comment by bragefuglseth** [comment]
I think the UI of the app is pretty cool and distinctive, so the icon could probably be a stylized version of it, like the current one, just more visually coherent with other GNOME icons.

**Comment by zhrexl** [comment]
I'd love it!
And if you have suggestions for the app design I'll gladly accept it too.

**Comment by zhrexl** [comment]
About the app name: I'll also accept name suggestions but the cools ones were already taken 😔

**Comment by bragefuglseth** [comment]
I'd be happy to assist with a more comprehensive rebrand. I'll open a separate issue about the name 👍
